### ISSUE TITLE
Clear API objects from unused fields. 

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#489]
There are several fields exist which never filled by the daemon, for more information see discussion in #470. Such fields should be removed, because they confused newbies.
The same should done with field `reputation` which is calculated in plugin `follow`, but filled in different API. The main problem that plugin `follow` can be disabled, and in this case `golosd` return wrong value.
- [x] Remove forever empty fields from `extended_account` #561 #589
- [x] Move `get_account_history` from `database_api` to `account_history` #573
- [x] Leave `get_content`, `get_content_replies`, `get_all_content_replies`, `get_account_votes`, `get_active_votes` in `social_network`, all other move to `tags?` plugin
- [x] `follow::get_account_reputations` should return reputations for list #574
- [x] Remove field `reputation` from all api objects
- [x] Remove empty strings from result of `database_api::get_active_witnesses()` #594
- [x] Remove unused indexes from account_index. #614 
- [x] Split account_history to two plugins: account_history and virtual_operation_history #613 
- [x] Create witness_api plugin. #618

**Comment by AKorpusenko** [comment]
#561 ref to point 1

**Comment by afalaleev** [comment]
Epic issue. It doesn't contains any changes. Move it to Done.
